# -*- coding: utf-8 -*-
"""Copy of Colaboratory Release Notes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGvDvrGP6IfphbeMzeuNtmJzI8eUfzgR
"""

!pip install scipy

import pandas as pd
import numpy as np
from scipy.spatial import cKDTree

df = pd.read_csv('/content/drive/MyDrive/urban_pluvial_flood_risk_dataset.csv')
df.head()

from google.colab import drive
drive.mount('/content/drive')

from scipy.spatial import cKDTree
import numpy as np

known = df[df['elevation_m'].notna()]
missing = df[df['elevation_m'].isna()]

tree = cKDTree(known[['longitude', 'latitude']])

distances, indices = tree.query(missing[['longitude', 'latitude']], k=5)

known_elev = known['elevation_m'].values
neighbor_elev = known_elev[indices]

weights = 1 / distances
weights[distances == 0] = 1e10

idw_values = np.sum(weights * neighbor_elev, axis=1) / np.sum(weights, axis=1)

df.loc[df['elevation_m'].isna(), 'elevation_m'] = idw_values

import matplotlib.pyplot as plt

plt.hist(df['elevation_m'], bins=30)
plt.xlabel("Elevation (m)")
plt.ylabel("Frequency")
plt.title("Elevation Distribution After IDW")
plt.show()

# Check missing count
print("Missing before:", df['drainage_density_km_per_km2'].isna().sum())

# Catchment-wise median imputation
df['drainage_density_km_per_km2'] = (
    df.groupby('catchment_id')['drainage_density_km_per_km2']
    .transform(lambda x: x.fillna(x.median()))
)

# Check again
print("Missing after:", df['drainage_density_km_per_km2'].isna().sum())

# Check missing count
print("Missing before:", df['drainage_density_km_per_km2'].isna().sum())

# Catchment-wise median imputation
df['drainage_density_km_per_km2'] = (
    df.groupby('catchment_id')['drainage_density_km_per_km2']
    .transform(lambda x: x.fillna(x.median()))
)

# Check again
print("Missing after:", df['drainage_density_km_per_km2'].isna().sum())

global_median = df['drainage_density_km_per_km2'].median()

df['drainage_density_km_per_km2'] = (
    df.groupby('catchment_id')['drainage_density_km_per_km2']
    .transform(lambda x: x.fillna(x.median()))
)

df['drainage_density_km_per_km2'].fillna(global_median, inplace=True)

import matplotlib.pyplot as plt

plt.hist(df['drainage_density_km_per_km2'], bins=30)
plt.xlabel("Drainage Density")
plt.ylabel("Frequency")
plt.title("Drainage Density After Imputation")
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Split known and missing
known = df[df['storm_drain_proximity_m'].notna()]
missing = df[df['storm_drain_proximity_m'].isna()]

features = [
    'elevation_m',
    'drainage_density_km_per_km2',
    'latitude',
    'longitude'
]

# Train model
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(known[features], known['storm_drain_proximity_m'])

# Predict missing
predicted_values = rf.predict(missing[features])

# Fill values
df.loc[df['storm_drain_proximity_m'].isna(),
       'storm_drain_proximity_m'] = predicted_values

import matplotlib.pyplot as plt

plt.hist(df['storm_drain_proximity_m'], bins=30)
plt.xlabel("Storm Drain Proximity (m)")
plt.ylabel("Frequency")
plt.title("After RF Imputation")
plt.show()

plt.hist(known['storm_drain_proximity_m'], bins=30, alpha=0.5, label="Original")
plt.hist(predicted_values, bins=30, alpha=0.5, label="Predicted")
plt.legend()
plt.title("Original vs Imputed Distribution")
plt.show()

df['storm_drain_missing'] = df['storm_drain_proximity_m'].isna().astype(int)

median_value = df['storm_drain_proximity_m'].median()
df['storm_drain_proximity_m'].fillna(median_value, inplace=True)

print("Remaining missing:",
      df['storm_drain_proximity_m'].isna().sum())

# Catchment-wise mode
df['soil_group'] = (
    df.groupby('catchment_id')['soil_group']
    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else np.nan))
)

# If still missing (rare case), fill with global mode
global_mode = df['soil_group'].mode()[0]
df['soil_group'].fillna(global_mode, inplace=True)

print("Remaining missing:", df['soil_group'].isna().sum())

import matplotlib.pyplot as plt

plt.hist(df['rainfall_intensity_mm_hr'], bins=30)
plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("Frequency")
plt.title("Rainfall Intensity After KNN")
plt.show()

print("Min:", df['rainfall_intensity_mm_hr'].min())
print("Max:", df['rainfall_intensity_mm_hr'].max())

df['elevation_m'] = (
    df.groupby('catchment_id')['elevation_m']
    .transform(lambda x: x.fillna(x.mean()))
)

# Fallback
df['elevation_m'].fillna(df['elevation_m'].mean(), inplace=True)

print("Remaining elevation missing:",
      df['elevation_m'].isna().sum())

df['drainage_density_km_per_km2'] = (
    df.groupby('catchment_id')['drainage_density_km_per_km2']
    .transform(lambda x: x.fillna(x.mean()))
)

df['drainage_density_km_per_km2'].fillna(
    df['drainage_density_km_per_km2'].mean(),
    inplace=True
)

print("Remaining drainage density missing:",
      df['drainage_density_km_per_km2'].isna().sum())

df['storm_drain_type'].fillna("No_Drain", inplace=True)

print("Remaining storm_drain_type missing:",
      df['storm_drain_type'].isna().sum())

df.isna().sum()

from google.colab import files
df.to_csv('flood_risk_cleaned2.csv', index=False)
files.download('flood_risk_cleaned2.csv')

print("Missing storm_drain_type:",
      df['storm_drain_type'].isna().sum())

df['storm_drain_type'].fillna("No_Drain", inplace=True)

df.drop(columns=['segment_id'], inplace=True)

print(df.columns)

df['storm_drain_missing'].value_counts()

df['risk_labels'] = df['risk_labels'].str.replace(r'event_\d{4}-\d{2}-\d{2}', '', regex=True)

df['risk_labels_list'] = df['risk_labels'].str.split('|')

from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
risk_encoded = mlb.fit_transform(df['risk_labels_list'])

risk_df = pd.DataFrame(risk_encoded, columns=mlb.classes_)
df = pd.concat([df, risk_df], axis=1)

risk_df.sum().sort_values(ascending=False)

df[df['risk_labels'] == ""]