# -*- coding: utf-8 -*-
"""flood_model-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aNvstriepJ6oDwzVmAuGR0K5TL6oA-Nz

random split
"""

import pandas as pd
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv("flood_model_ready_final.csv")

# Define input and output columns
input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

# Keep only required columns
data = df[input_cols + output_cols].copy()

# Optional: drop missing values
data = data.dropna()

# Inputs and outputs
X = data[input_cols]
y = data[output_cols]

# Random split: 80% train, 20% test
# random_state=42 makes the split reproducible
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

# Combine back if you want full train/test datasets
train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)

# Save split files
train_df.to_csv("flood_random_split_train.csv", index=False)
test_df.to_csv("flood_random_split_test.csv", index=False)

# Show split info
print("Total rows:", len(data))
print("Train rows:", len(train_df))
print("Test rows:", len(test_df))

print("\nInput variables:")
print(input_cols)

print("\nOutput variables:")
print(output_cols)

"""Our chosen inputs:

y_low_lying

y_extreme_rain_history

are most likely binary/categorical indicators like 0 and 1. Those do not have a circular relationship, so cyclical encoding would be meaningless.

lightbgm - training
"""

import pandas as pd
import joblib
from lightgbm import LGBMClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TRAIN DATA
# =========================
train_df = pd.read_csv("train_split.csv")

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_train = train_df[input_cols]
Y_train = train_df[output_cols]

# =========================
# MODEL
# =========================
base_model = LGBMClassifier(
    n_estimators=100,
    learning_rate=0.05,
    random_state=42
)

model = MultiOutputClassifier(base_model)

# =========================
# TRAIN
# =========================
model.fit(X_train, Y_train)

# Save model
joblib.dump(model, "lightgbm_multioutput_model.pkl")

# =========================
# TRAIN PREDICTIONS
# =========================
Y_train_pred = model.predict(X_train)
Y_train_pred_df = pd.DataFrame(Y_train_pred, columns=output_cols, index=Y_train.index)

# =========================
# TRAIN METRICS
# =========================
print("\n========== LIGHTGBM TRAINING METRICS ==========\n")

exact_match_train = accuracy_score(Y_train, Y_train_pred_df)
hamming_train = hamming_loss(Y_train, Y_train_pred_df)

print("Exact Match Accuracy (Train):", exact_match_train)
print("Hamming Loss (Train):", hamming_train)

for col in output_cols:
    f1 = f1_score(Y_train[col], Y_train_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_train[col], Y_train_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TRAIN PREDICTIONS
# =========================
train_results = pd.concat(
    [
        X_train.reset_index(drop=True),
        Y_train.reset_index(drop=True).add_prefix("actual_"),
        Y_train_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

train_results.to_csv("lightgbm_train_predictions.csv", index=False)

print("\nSaved model: lightgbm_multioutput_model.pkl")
print("Saved predictions: lightgbm_train_predictions.csv")

from google.colab import drive
drive.mount('/content/drive')

"""testing"""

import pandas as pd
import joblib
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TEST DATA
# =========================
test_df = pd.read_csv("test_split.csv")

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_test = test_df[input_cols]
Y_test = test_df[output_cols]

# =========================
# LOAD MODEL
# =========================
model = joblib.load("lightgbm_multioutput_model.pkl")

# =========================
# TEST PREDICTIONS
# =========================
Y_test_pred = model.predict(X_test)
Y_test_pred_df = pd.DataFrame(Y_test_pred, columns=output_cols, index=Y_test.index)

# =========================
# TEST METRICS
# =========================
print("\n========== LIGHTGBM TESTING METRICS ==========\n")

exact_match_test = accuracy_score(Y_test, Y_test_pred_df)
hamming_test = hamming_loss(Y_test, Y_test_pred_df)

print("Exact Match Accuracy (Test):", exact_match_test)
print("Hamming Loss (Test):", hamming_test)

for col in output_cols:
    f1 = f1_score(Y_test[col], Y_test_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_test[col], Y_test_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TEST PREDICTIONS
# =========================
test_results = pd.concat(
    [
        X_test.reset_index(drop=True),
        Y_test.reset_index(drop=True).add_prefix("actual_"),
        Y_test_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

test_results.to_csv("lightgbm_test_predictions.csv", index=False)

print("\nSaved predictions: lightgbm_test_predictions.csv")

"""catboost - training"""

pip install catboost joblib pandas scikit-learn

"""catboost- training"""

import pandas as pd
import joblib
from catboost import CatBoostClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TRAIN DATA
# =========================
train_df = pd.read_csv("train_split.csv")

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_train = train_df[input_cols]
Y_train = train_df[output_cols]

# =========================
# MODEL
# =========================
base_model = CatBoostClassifier(
    iterations=200,
    learning_rate=0.05,
    depth=6,
    loss_function="Logloss",
    verbose=0,
    random_seed=42
)

model = MultiOutputClassifier(base_model)

# =========================
# TRAIN
# =========================
model.fit(X_train, Y_train)

# Save model
joblib.dump(model, "catboost_multioutput_model.pkl")

# =========================
# TRAIN PREDICTIONS
# =========================
Y_train_pred = model.predict(X_train)
Y_train_pred_df = pd.DataFrame(Y_train_pred, columns=output_cols, index=Y_train.index)

# =========================
# TRAIN METRICS
# =========================
print("\n========== CATBOOST TRAINING METRICS ==========\n")

exact_match_train = accuracy_score(Y_train, Y_train_pred_df)
hamming_train = hamming_loss(Y_train, Y_train_pred_df)

print("Exact Match Accuracy (Train):", exact_match_train)
print("Hamming Loss (Train):", hamming_train)

for col in output_cols:
    f1 = f1_score(Y_train[col], Y_train_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_train[col], Y_train_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TRAIN PREDICTIONS
# =========================
train_results = pd.concat(
    [
        X_train.reset_index(drop=True),
        Y_train.reset_index(drop=True).add_prefix("actual_"),
        Y_train_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

train_results.to_csv("catboost_train_predictions.csv", index=False)

print("\nSaved model: catboost_multioutput_model.pkl")
print("Saved predictions: catboost_train_predictions.csv")

"""testing"""

import pandas as pd
import joblib
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TEST DATA
# =========================
test_df = pd.read_csv("test_split.csv")

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_test = test_df[input_cols]
Y_test = test_df[output_cols]

# =========================
# LOAD MODEL
# =========================
model = joblib.load("catboost_multioutput_model.pkl")

# =========================
# TEST PREDICTIONS
# =========================
Y_test_pred = model.predict(X_test)
Y_test_pred_df = pd.DataFrame(Y_test_pred, columns=output_cols, index=Y_test.index)

# =========================
# TEST METRICS
# =========================
print("\n========== CATBOOST TESTING METRICS ==========\n")

exact_match_test = accuracy_score(Y_test, Y_test_pred_df)
hamming_test = hamming_loss(Y_test, Y_test_pred_df)

print("Exact Match Accuracy (Test):", exact_match_test)
print("Hamming Loss (Test):", hamming_test)

for col in output_cols:
    f1 = f1_score(Y_test[col], Y_test_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_test[col], Y_test_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TEST PREDICTIONS
# =========================
test_results = pd.concat(
    [
        X_test.reset_index(drop=True),
        Y_test.reset_index(drop=True).add_prefix("actual_"),
        Y_test_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

test_results.to_csv("catboost_test_predictions.csv", index=False)

print("\nSaved predictions: catboost_test_predictions.csv")

"""MLP- Training"""

import pandas as pd
import joblib
from sklearn.neural_network import MLPClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TRAIN DATA
# =========================
train_df = pd.read_csv("train_split.csv")   # or flood_random_split_train.csv

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_train = train_df[input_cols]
Y_train = train_df[output_cols]

# =========================
# SCALE INPUTS
# =========================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Save scaler
joblib.dump(scaler, "mlp_scaler.pkl")

# =========================
# MODEL
# =========================
base_model = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    activation="relu",
    solver="adam",
    max_iter=500,
    random_state=42
)

model = MultiOutputClassifier(base_model)

# =========================
# TRAIN
# =========================
model.fit(X_train_scaled, Y_train)

# Save model
joblib.dump(model, "mlp_multioutput_model.pkl")

# =========================
# TRAIN PREDICTIONS
# =========================
Y_train_pred = model.predict(X_train_scaled)
Y_train_pred_df = pd.DataFrame(Y_train_pred, columns=output_cols, index=Y_train.index)

# =========================
# TRAIN METRICS
# =========================
print("\n========== MLP TRAINING METRICS ==========\n")

exact_match_train = accuracy_score(Y_train, Y_train_pred_df)
hamming_train = hamming_loss(Y_train, Y_train_pred_df)

print("Exact Match Accuracy (Train):", exact_match_train)
print("Hamming Loss (Train):", hamming_train)

for col in output_cols:
    f1 = f1_score(Y_train[col], Y_train_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_train[col], Y_train_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TRAIN PREDICTIONS
# =========================
train_results = pd.concat(
    [
        pd.DataFrame(X_train_scaled, columns=input_cols),
        Y_train.reset_index(drop=True).add_prefix("actual_"),
        Y_train_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

train_results.to_csv("mlp_train_predictions.csv", index=False)

print("\nSaved scaler: mlp_scaler.pkl")
print("Saved model: mlp_multioutput_model.pkl")
print("Saved predictions: mlp_train_predictions.csv")

"""MLP- testing"""

import pandas as pd
import joblib
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TEST DATA
# =========================
test_df = pd.read_csv("test_split.csv")   # or flood_random_split_test.csv

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_test = test_df[input_cols]
Y_test = test_df[output_cols]

# =========================
# LOAD SCALER + MODEL
# =========================
scaler = joblib.load("mlp_scaler.pkl")
model = joblib.load("mlp_multioutput_model.pkl")

X_test_scaled = scaler.transform(X_test)

# =========================
# TEST PREDICTIONS
# =========================
Y_test_pred = model.predict(X_test_scaled)
Y_test_pred_df = pd.DataFrame(Y_test_pred, columns=output_cols, index=Y_test.index)

# =========================
# TEST METRICS
# =========================
print("\n========== MLP TESTING METRICS ==========\n")

exact_match_test = accuracy_score(Y_test, Y_test_pred_df)
hamming_test = hamming_loss(Y_test, Y_test_pred_df)

print("Exact Match Accuracy (Test):", exact_match_test)
print("Hamming Loss (Test):", hamming_test)

for col in output_cols:
    f1 = f1_score(Y_test[col], Y_test_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_test[col], Y_test_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TEST PREDICTIONS
# =========================
test_results = pd.concat(
    [
        pd.DataFrame(X_test_scaled, columns=input_cols),
        Y_test.reset_index(drop=True).add_prefix("actual_"),
        Y_test_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

test_results.to_csv("mlp_test_predictions.csv", index=False)

print("\nSaved predictions: mlp_test_predictions.csv")

""" **Tabnet**"""

!pip install pandas scikit-learn joblib
!pip install pytorch-tabnet torch

"""training (tabnet)"""

import pandas as pd
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TRAIN DATA
# =========================
train_df = pd.read_csv("train_split.csv")   # or "flood_random_split_train.csv"

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_train = train_df[input_cols].values
Y_train = train_df[output_cols].copy()

# =========================
# TRAIN ONE MODEL PER TARGET
# =========================
train_preds = {}

for col in output_cols:
    print(f"\nTraining TabNet for: {col}")

    model = TabNetClassifier(seed=42, verbose=0)

    model.fit(
        X_train=X_train,
        y_train=Y_train[col].values,
        max_epochs=100,
        patience=10,
        batch_size=256,
        virtual_batch_size=128
    )

    # Save each target model
    model.save_model(f"tabnet_{col}")

    # Predict on training data
    pred = model.predict(X_train)
    train_preds[col] = pred

# =========================
# TRAIN PREDICTIONS DATAFRAME
# =========================
Y_train_pred_df = pd.DataFrame(train_preds, index=Y_train.index)

# =========================
# TRAIN METRICS
# =========================
print("\n========== TABNET TRAINING METRICS ==========\n")

exact_match_train = accuracy_score(Y_train, Y_train_pred_df)
hamming_train = hamming_loss(Y_train, Y_train_pred_df)

print("Exact Match Accuracy (Train):", exact_match_train)
print("Hamming Loss (Train):", hamming_train)

for col in output_cols:
    f1 = f1_score(Y_train[col], Y_train_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_train[col], Y_train_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TRAIN PREDICTIONS
# =========================
train_results = pd.concat(
    [
        pd.DataFrame(X_train, columns=input_cols),
        Y_train.reset_index(drop=True).add_prefix("actual_"),
        Y_train_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

train_results.to_csv("tabnet_train_predictions.csv", index=False)

print("\nSaved predictions: tabnet_train_predictions.csv")
print("Saved models:")
print("tabnet_y_monitor.zip")
print("tabnet_y_ponding_hotspot.zip")
print("tabnet_y_sparse_drainage.zip")

"""testing"""

import pandas as pd
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.metrics import accuracy_score, f1_score, hamming_loss, confusion_matrix

# =========================
# LOAD TEST DATA
# =========================
test_df = pd.read_csv("test_split.csv")   # or "flood_random_split_test.csv"

input_cols = ["y_low_lying", "y_extreme_rain_history"]
output_cols = ["y_monitor", "y_ponding_hotspot", "y_sparse_drainage"]

X_test = test_df[input_cols].values
Y_test = test_df[output_cols].copy()

# =========================
# LOAD MODELS AND PREDICT
# =========================
test_preds = {}

for col in output_cols:
    model = TabNetClassifier()
    model.load_model(f"tabnet_{col}.zip")

    pred = model.predict(X_test)
    test_preds[col] = pred

Y_test_pred_df = pd.DataFrame(test_preds, index=Y_test.index)

# =========================
# TEST METRICS
# =========================
print("\n========== TABNET TESTING METRICS ==========\n")

exact_match_test = accuracy_score(Y_test, Y_test_pred_df)
hamming_test = hamming_loss(Y_test, Y_test_pred_df)

print("Exact Match Accuracy (Test):", exact_match_test)
print("Hamming Loss (Test):", hamming_test)

for col in output_cols:
    f1 = f1_score(Y_test[col], Y_test_pred_df[col], zero_division=0)
    cm = confusion_matrix(Y_test[col], Y_test_pred_df[col])

    print(f"\n----- {col} -----")
    print("F1-score:", f1)
    print("Confusion Matrix:\n", cm)

# =========================
# SAVE TEST PREDICTIONS
# =========================
test_results = pd.concat(
    [
        pd.DataFrame(X_test, columns=input_cols),
        Y_test.reset_index(drop=True).add_prefix("actual_"),
        Y_test_pred_df.reset_index(drop=True).add_prefix("pred_")
    ],
    axis=1
)

test_results.to_csv("tabnet_test_predictions.csv", index=False)

print("\nSaved predictions: tabnet_test_predictions.csv")

import numpy as np
import matplotlib.pyplot as plt

# ====== CONVERT TO NUMPY ======
y_true = y_test.values if hasattr(y_test, "values") else np.array(y_test)

# ====== FLATTEN ======
observed = y_true.flatten()

models = {}

if "y_pred_lgbm" in globals():
    models["LGBM"] = np.array(y_pred_lgbm).flatten()

if "y_pred_rf" in globals():
    models["RF"] = np.array(y_pred_rf).flatten()

if "y_pred_mlp" in globals():
    models["MLP"] = np.array(y_pred_mlp).flatten()

if "y_pred_tabnet" in globals():
    models["TabNet"] = np.array(y_pred_tabnet).flatten()

# ====== CHECK ======
if len(models) == 0:
    raise ValueError("❌ No prediction variables found!")

# ====== STATS FUNCTION ======
def taylor_stats(ref, pred):
    std = np.std(pred, ddof=1)
    corr = np.corrcoef(ref, pred)[0, 1]
    return std, corr

# ====== REFERENCE ======
std_ref = np.std(observed, ddof=1)

# ====== PLOT ======
plt.figure(figsize=(7,7))
ax = plt.subplot(111, polar=True)

# Reference point
ax.plot(0, std_ref, 'ro', label='Actual')

# Plot each model
for name, pred in models.items():
    std, corr = taylor_stats(observed, pred)
    theta = np.arccos(np.clip(corr, -1, 1))
    ax.plot(theta, std, 'o', label=name)

# Formatting
ax.set_theta_direction(-1)
ax.set_theta_zero_location('E')

corr_ticks = np.linspace(0, 1, 6)
ax.set_thetagrids(np.degrees(np.arccos(corr_ticks)), labels=np.round(corr_ticks,2))

ax.set_title("Taylor Diagram")

ax.legend()
plt.show()

"""Correlation matrix"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load your dataset
df = pd.read_csv("flood_model_ready_final.csv")

# Select only numeric columns
df_numeric = df.select_dtypes(include=['float64', 'int64'])

# Compute correlation
corr = df_numeric.corr()

# Plot
plt.figure(figsize=(12, 10), dpi=300)  # HIGH RESOLUTION
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)

plt.title("Correlation Matrix of Flood Features", fontsize=16)
plt.tight_layout()

# Save in HIGH QUALITY
plt.savefig("correlation_matrix.png", dpi=300)
plt.savefig("correlation_matrix.pdf")  # best for papers

plt.show()

plt.figure(figsize=(2, 2), dpi=300)

sns.scatterplot(
    data=df,
    x='rainfall_intensity_mm_hr',
    y='y_ponding_hotspot'   # or any target column
)

plt.title("Rainfall Intensity vs Ponding Hotspot")
plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("Ponding Hotspot")

plt.tight_layout()
plt.savefig("scatter_rainfall_vs_ponding.png", dpi=300)
plt.show()

import numpy as np

plt.figure(figsize=(6,2), dpi=300)

sns.scatterplot(
    data=df,
    x='rainfall_intensity_mm_hr',
    y=df['y_ponding_hotspot'] + np.random.uniform(-0.05, 0.05, size=len(df)),
    alpha=0.6
)

plt.title("Rainfall vs Ponding Hotspot")
plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("Ponding Hotspot")

plt.savefig("better_scatter.png", dpi=300)
plt.show()

plt.figure(figsize=(2,2), dpi=300)

sns.boxplot(
    data=df,
    x='y_ponding_hotspot',
    y='rainfall_intensity_mm_hr'
)

plt.title("Rainfall Intensity vs Ponding Hotspot")
plt.xlabel("Ponding Hotspot (0 = No, 1 = Yes)")
plt.ylabel("Rainfall Intensity (mm/hr)")

plt.savefig("boxplot_rainfall.png", dpi=300)
plt.show()

plt.figure(figsize=(6,6), dpi=300)

sns.violinplot(
    data=df,
    x='y_ponding_hotspot',
    y='rainfall_intensity_mm_hr'
)

# plt.title("")
plt.savefig("violin_plot.png", dpi=300)
plt.show()

"""The plot shows two distributions — 0 (no flooding) and 1 (flooding) — for rainfall intensity.

For no flooding (0), most of the values are concentrated in the lower rainfall range (around 20–50 mm/hr). The shape is narrower and does not extend very high.

For flooding (1), the distribution is shifted upward, meaning rainfall values are generally higher. The plot also extends to very high rainfall values (above 100 mm/hr).

The middle part (median) of the flooded side is clearly higher than the non-flooded side, showing that flooding cases usually experience stronger rainfall.

The flooded side is also wider, indicating that rainfall values are more spread out and variable when flooding occurs.

There is a visible overlap region (around 30–70 mm/hr) where both flooding and non-flooding cases exist.

This overlap shows that some areas do not flood even with moderate rainfall, and some areas flood even without extremely high rainfall.
"""

plt.figure(figsize=(3, 3), dpi=300)

sns.scatterplot(
    data=df,
    x='rainfall_intensity_mm_hr',
    y='elevation_m',
    hue='y_ponding_hotspot',  # 0 or 1
    size='drainage_density_km_per_km2',
    palette='coolwarm',
    sizes=(20, 200),
    alpha=0.7
)

plt.title("Multi-Factor Flood Risk Visualization", fontsize=16)
plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("Elevation (m)")

plt.legend(title="Ponding Hotspot", bbox_to_anchor=(1.05, 1))
plt.tight_layout()

plt.savefig("multifactor_scatter.png", dpi=300)
plt.show()

"""Low-lying areas are highly prone to ponding hotspots .

 Flooding occurs when:
High rainfall + Low elevation + Poor drainage
"""

from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import matplotlib.pyplot as plt

# Features & target
X = df.select_dtypes(include=['int64', 'float64']).drop(columns=[
    'y_ponding_hotspot','y_low_lying','y_sparse_drainage','y_extreme_rain_history'
])
y = df['y_ponding_hotspot']

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

# Get importance
importances = pd.Series(model.feature_importances_, index=X.columns)
importances = importances.sort_values(ascending=False)  # better for vertical

# Plot
plt.figure(figsize=(12, 6), dpi=600)  # wider layout for vertical bars
importances.plot(kind='bar')

plt.title("Feature Importance for Ponding Hotspot Prediction")
plt.ylabel("Importance Score")
plt.xlabel("Features")

plt.xticks(rotation=45, ha='right')  # rotate labels for readability

plt.tight_layout()

# Save high-resolution
plt.savefig("feature_importance.png", dpi=600)
plt.savefig("feature_importance.pdf")

plt.show()

from sklearn.model_selection import learning_curve
import numpy as np

train_sizes, train_scores, test_scores = learning_curve(
    model, X, y,
    cv=5,
    scoring='accuracy',
    train_sizes=np.linspace(0.1, 1.0, 10),
    n_jobs=-1
)

train_mean = train_scores.mean(axis=1)
test_mean = test_scores.mean(axis=1)

# Plot
plt.figure(figsize=(8,6), dpi=600)

plt.plot(train_sizes, train_mean, label="Training Score")
plt.plot(train_sizes, test_mean, label="Validation Score")

plt.xlabel("Training Size")
plt.ylabel("Accuracy")
plt.title("Learning Curve")

plt.legend()
plt.grid()

plt.tight_layout()
plt.savefig("learning_curve.png", dpi=600)
plt.savefig("learning_curve.pdf")

plt.show()

from sklearn.model_selection import learning_curve
import numpy as np

train_sizes, train_scores, test_scores = learning_curve(
    model, X, y,
    cv=5,
    scoring='accuracy',
    train_sizes=np.linspace(0.1, 1.0, 10),
    n_jobs=-1
)

train_mean = train_scores.mean(axis=1)
test_mean = test_scores.mean(axis=1)

# Plot
plt.figure(figsize=(8,6), dpi=600)

plt.plot(train_sizes, train_mean, label="Training Score")
plt.plot(train_sizes, test_mean, label="Validation Score")

plt.xlabel("Training Size")
plt.ylabel("Accuracy")
plt.title("Learning Curve")

plt.legend()
plt.grid()

plt.tight_layout()
plt.savefig("learning_curve.png", dpi=600)
plt.savefig("learning_curve.pdf")

plt.show()

!pip install catboost lightgbm

# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.neural_network import MLPClassifier

# ================================
# 2. LOAD DATA
# ================================
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# ================================
# 3. PREPARE DATA
# ================================
X = df.select_dtypes(include=['int64','float64']).drop(columns=[
    'y_ponding_hotspot','y_low_lying','y_sparse_drainage','y_extreme_rain_history'
], errors='ignore')

y = df['y_ponding_hotspot']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# 4. TRAIN MODELS
# ================================
lgbm = LGBMClassifier()
cat = CatBoostClassifier(verbose=0)
mlp = MLPClassifier(max_iter=500)

lgbm.fit(X_train, y_train)
cat.fit(X_train, y_train)
mlp.fit(X_train, y_train)

print("Models trained ✅")

# ================================
# 5. GET PROBABILITIES (IMPORTANT 🔥)
# ================================
lgbm_pred = lgbm.predict_proba(X_test)[:,1]
cat_pred = cat.predict_proba(X_test)[:,1]
mlp_pred = mlp.predict_proba(X_test)[:,1]

# ================================
# 6. COMBINE DATA
# ================================
df_lgbm = pd.DataFrame({'prediction': lgbm_pred, 'model': 'LightGBM'})
df_cat = pd.DataFrame({'prediction': cat_pred, 'model': 'CatBoost'})
df_mlp = pd.DataFrame({'prediction': mlp_pred, 'model': 'MLP'})

combined_df = pd.concat([df_lgbm, df_cat, df_mlp])

# ================================
# 7. DENSITY PLOT (FIXED + 600 DPI)
# ================================
plt.figure(figsize=(10,6), dpi=600)

sns.kdeplot(
    data=combined_df,
    x='prediction',
    hue='model',
    fill=True,
    common_norm=False,
    alpha=0.5
)

plt.xlim(0,1)  # IMPORTANT FIX

plt.title("Density Distribution of Model Predictions", fontsize=14)
plt.xlabel("Predicted Probability of Flood")
plt.ylabel("Density")

plt.tight_layout()

plt.savefig("density_models_advanced.png", dpi=600)
plt.savefig("density_models_advanced.pdf")

plt.show()

sensitivity analysis

# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# ================================
# 2. UPLOAD FILE
# ================================
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset Loaded ✅")

# ================================
# 3. PREPARE DATA
# ================================
X = df.select_dtypes(include=['int64','float64']).drop(columns=[
    'y_ponding_hotspot','y_low_lying','y_sparse_drainage','y_extreme_rain_history'
], errors='ignore')

y = df['y_ponding_hotspot']

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# 4. TRAIN MODEL (RF BEST FOR SENSITIVITY)
# ================================
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# ================================
# 5. DENSITY PLOT (600 DPI)
# ================================
rf_pred = model.predict_proba(X_test)[:,1]

df_plot = pd.DataFrame({
    'prediction': rf_pred
})

plt.figure(figsize=(10,6), dpi=600)

sns.kdeplot(
    data=df_plot,
    x='prediction',
    fill=True,
    alpha=0.5
)

plt.title("Density Distribution of Predictions")
plt.xlabel("Predicted Flood Probability")
plt.ylabel("Density")

plt.tight_layout()
plt.savefig("density_plot.png", dpi=600)
plt.show()

# ================================
# 6. SENSITIVITY ANALYSIS (FIXED 🔥)
# ================================
# Choose one row as base
base = X_test.iloc[0].copy()

rain_range = np.linspace(
    df['rainfall_intensity_mm_hr'].min(),
    df['rainfall_intensity_mm_hr'].max(),
    100
)

preds = []

for r in rain_range:
    temp = base.copy()
    temp['rainfall_intensity_mm_hr'] = r  # vary rainfall

    pred = model.predict_proba([temp])[0][1]
    preds.append(pred)

# Plot sensitivity
plt.figure(figsize=(10,6), dpi=600)

plt.plot(rain_range, preds)

plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("Predicted Flood Probability")
plt.title("Sensitivity Analysis: Rainfall vs Flood Risk")

plt.tight_layout()
plt.savefig("sensitivity_plot.png", dpi=600)
plt.show()

print("All plots generated ✅")

"""Label Co-occurrence Analysis"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv('flood_model_ready_final.csv')

# Select label columns
label_cols = [col for col in df.columns if col.startswith('y_')]

label_matrix = df[label_cols]

# Co-occurrence matrix
co_occurrence = label_matrix.T.dot(label_matrix)

# Plot
plt.figure(figsize=(8,6))
sns.heatmap(co_occurrence, annot=True, fmt='d', cmap='Blues')
plt.title("Label Co-occurrence Matrix")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load your dataset
df = pd.read_csv('flood_model_ready_final.csv')   # ← change filename
# Target column (change if needed)
target_col = 'y_ponding_hotspot'

# Count values
counts = df[target_col].value_counts().sort_index()

# Plot
plt.figure(figsize=(6,5))

sns.barplot(
    x=counts.index,
    y=counts.values,
    palette=['#1f77b4', '#d62728']  # Blue = No Flood, Red = Flood
)

# Labels
plt.xlabel('Class Label', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.title('Class Distribution of Flood vs Non-Flood', fontsize=14)

# Custom x labels
plt.xticks([0,1], ['Non-Flood (0)', 'Flood (1)'])

# Add value labels on top
for i, v in enumerate(counts.values):
    plt.text(i, v + max(counts.values)*0.01, str(v), ha='center', fontsize=11)

# Style
plt.grid(axis='y', linestyle='--', alpha=0.5)

# Save high-quality image
plt.tight_layout()
plt.savefig('class_distribution.png', dpi=600)

plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# Dictionary of models (already trained)
models = {
    "LightGBM": lgb_model,
    "CatBoost": cat_model,
    "MLP": mlp_model,
    "TabNet": tabnet_model
}

plt.figure(figsize=(7,6))

# Loop through models
for name, model in models.items():

    # Get predicted probabilities
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        # For models like TabNet
        y_prob = model.predict(X_test).ravel()

    # Compute ROC
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    # Plot
    plt.plot(fpr, tpr, linewidth=2, label=f"{name} (AUC = {roc_auc:.3f})")

# Diagonal line (random model)
plt.plot([0,1], [0,1], linestyle='--', linewidth=1)

# Labels
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.title("ROC Curve Comparison of Models", fontsize=14)

# Legend
plt.legend(fontsize=10, loc="lower right")

# Grid
plt.grid(alpha=0.3)

# Save high-quality image
plt.tight_layout()
plt.savefig("roc_curve.png", dpi=600)

plt.show()

"""Class Imbalance Analysis"""

# Label frequency
label_counts = label_matrix.sum().sort_values(ascending=False)

# Plot
plt.figure(figsize=(10,5))
label_counts.plot(kind='bar')
plt.title("Label Distribution")
plt.ylabel("Frequency")
plt.show()

# Print imbalance ratio
print(label_counts)

from scipy.stats import ttest_ind, mannwhitneyu
import numpy as np

# Recreate num_cols
num_cols = df.select_dtypes(include=np.number).columns.tolist()
num_cols = [col for col in num_cols if col != 'flood']

print("\n--- STATISTICAL TEST RESULTS (FIXED) ---")

for feature in num_cols:

    flooded = df[df['flood'] == 1][feature].dropna()
    non_flooded = df[df['flood'] == 0][feature].dropna()

    # Check sample size
    if len(flooded) < 10 or len(non_flooded) < 10:
        print(f"\nFeature: {feature}")
        print("❌ Skipped (Insufficient samples)")
        continue

    # Check variance
    if flooded.nunique() <= 1 or non_flooded.nunique() <= 1:
        print(f"\nFeature: {feature}")
        print("❌ Skipped (No variation)")
        continue

    try:
        t_stat, p_val = ttest_ind(flooded, non_flooded, equal_var=False)
        u_stat, p_val2 = mannwhitneyu(flooded, non_flooded)

        print(f"\nFeature: {feature}")
        print(f"T-test p-value: {p_val:.5f}")
        print(f"Mann-Whitney p-value: {p_val2:.5f}")

    except Exception as e:
        print(f"\nFeature: {feature}")
        print("❌ Error:", e)

from sklearn.metrics import classification_report

# Assume:
# y_true = true labels (label_matrix)
# y_pred = model predictions (same shape)

# Example placeholder:
# y_pred = model.predict(X_test)

# Convert to DataFrame
y_true_df = pd.DataFrame(y_true, columns=mlb.classes_)
y_pred_df = pd.DataFrame(y_pred, columns=mlb.classes_)

# Per-label performance
for col in y_true_df.columns:
    print(f"\nLabel: {col}")
    print(classification_report(y_true_df[col], y_pred_df[col]))

# Find misclassified samples
errors = (y_true_df != y_pred_df)

# Count errors per label
error_count = errors.sum().sort_values(ascending=False)
print("\nErrors per label:\n", error_count)

pip install SkillMetrics

model_lgbm.fit(X_train, y_train)
y_pred_lgbm = model_lgbm.predict(X_test)

print("LGBM done:", y_pred_lgbm.shape)

import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, average_precision_score
plt.figure(figsize=(8,6))

for name, probs in models.items():
    precision, recall, _ = precision_recall_curve(
        y_test.values.flatten(), probs.flatten()
    )
    ap = average_precision_score(y_test.values.flatten(), probs.flatten())

    plt.plot(recall, precision, label=f"{name} (AP = {ap:.2f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve - Model Comparison")
plt.legend()
plt.show()

# ================================
# 0. INSTALL REQUIRED LIBRARIES
# ================================
!pip install lightgbm catboost pytorch-tabnet -q

# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier

# ================================
# 2. LOAD DATA (UPLOAD FILE)
# ================================
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset Loaded ✅")

# ================================
# 3. PREPARE DATA
# ================================
X = df.select_dtypes(include=['int64','float64']).drop(columns=[
    'y_ponding_hotspot','y_low_lying','y_sparse_drainage','y_extreme_rain_history'
], errors='ignore')

y = df['y_ponding_hotspot']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# 4. TRAIN MODELS
# ================================
lgbm = LGBMClassifier()
cat = CatBoostClassifier(verbose=0)
mlp = MLPClassifier(max_iter=500)

# TabNet needs numpy arrays
tabnet = TabNetClassifier(verbose=0)

# Train
lgbm.fit(X_train, y_train)
cat.fit(X_train, y_train)
mlp.fit(X_train, y_train)

tabnet.fit(
    X_train.values, y_train.values,
    eval_set=[(X_test.values, y_test.values)],
    patience=10,
    max_epochs=100
)

print("All Models Trained ✅")

# ================================
# 5. GET PROBABILITIES (IMPORTANT)
# ================================
lgbm_pred = lgbm.predict_proba(X_test)[:,1]
cat_pred = cat.predict_proba(X_test)[:,1]
mlp_pred = mlp.predict_proba(X_test)[:,1]
tab_pred = tabnet.predict_proba(X_test.values)[:,1]

# ================================
# 6. COMBINE DATA
# ================================
df_lgbm = pd.DataFrame({'prediction': lgbm_pred, 'model': 'LightGBM'})
df_cat = pd.DataFrame({'prediction': cat_pred, 'model': 'CatBoost'})
df_mlp = pd.DataFrame({'prediction': mlp_pred, 'model': 'MLP'})
df_tab = pd.DataFrame({'prediction': tab_pred, 'model': 'TabNet'})

combined_df = pd.concat([df_lgbm, df_cat, df_mlp, df_tab])

# ================================
# 7. DENSITY PLOT (600 DPI 🔥)
# ================================
plt.figure(figsize=(10,6), dpi=600)

sns.kdeplot(
    data=combined_df,
    x='prediction',
    hue='model',
    fill=True,
    common_norm=False,
    alpha=0.5
)

plt.xlim(0,1)

plt.title("Density Distribution of Model Predictions", fontsize=14)
plt.xlabel("Predicted Probability of Flood")
plt.ylabel("Density")

plt.legend(title="Model")

plt.tight_layout()

# SAVE HIGH QUALITY
plt.savefig("density_models_600dpi.png", dpi=600)
plt.savefig("density_models_600dpi.pdf")

plt.show()

print("600 DPI Density Plot Generated ✅")

# ================================
# 0. INSTALL LIBRARIES
# ================================
!pip install lightgbm catboost pytorch-tabnet -q

# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier

# ================================
# 2. LOAD DATA
# ================================
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset Loaded ✅")

# ================================
# 3. PREPARE DATA
# ================================
X = df.select_dtypes(include=['int64','float64']).drop(columns=[
    'y_ponding_hotspot','y_low_lying','y_sparse_drainage','y_extreme_rain_history'
], errors='ignore')

y = df['y_ponding_hotspot']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# 4. TRAIN MODELS
# ================================
lgbm = LGBMClassifier()
cat = CatBoostClassifier(verbose=0)
mlp = MLPClassifier(max_iter=500)
tabnet = TabNetClassifier(verbose=0)

lgbm.fit(X_train, y_train)
cat.fit(X_train, y_train)
mlp.fit(X_train, y_train)

tabnet.fit(
    X_train.values, y_train.values,
    eval_set=[(X_test.values, y_test.values)],
    patience=10,
    max_epochs=100
)

print("Models trained ✅")

# ================================
# 5. GET PROBABILITIES
# ================================
lgbm_pred = lgbm.predict_proba(X_test)[:,1]
cat_pred = cat.predict_proba(X_test)[:,1]
mlp_pred = mlp.predict_proba(X_test)[:,1]
tab_pred = tabnet.predict_proba(X_test.values)[:,1]

# ================================
# 6. COMBINE DATA
# ================================
combined_df = pd.DataFrame({
    'prediction': np.concatenate([lgbm_pred, cat_pred, mlp_pred, tab_pred]),
    'model': (['LightGBM']*len(lgbm_pred) +
              ['CatBoost']*len(cat_pred) +
              ['MLP']*len(mlp_pred) +
              ['TabNet']*len(tab_pred))
})

# ================================
# 7. DENSITY PLOT (FINAL FIX 🔥)
# ================================
plt.figure(figsize=(10,6), dpi=600)

palette = {
    'LightGBM': 'blue',
    'CatBoost': 'green',
    'MLP': 'red',
    'TabNet': 'orange'
}

ax = sns.kdeplot(
    data=combined_df,
    x='prediction',
    hue='model',
    fill=True,
    common_norm=False,
    alpha=0.5,
    palette=palette
)

plt.xlim(0,1)

plt.title("Density Distribution of Model Predictions", fontsize=14)
plt.xlabel("Predicted Probability of Flood")
plt.ylabel("Density")

# ✅ FIXED LEGEND (NO ERROR)
handles, labels = ax.get_legend_handles_labels()
plt.legend(handles=handles, labels=labels, title="Model",
           bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()

# SAVE HIGH QUALITY
plt.savefig("density_models_final.png", dpi=600, bbox_inches='tight')
plt.savefig("density_models_final.pdf", bbox_inches='tight')

plt.show()

print("Final Plot with Model Names Generated ✅")

# ================================
# 0. INSTALL LIBRARIES
# ================================
!pip install lightgbm catboost pytorch-tabnet -q

# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from pytorch_tabnet.tab_model import TabNetClassifier

# ================================
# 2. LOAD DATA
# ================================
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset Loaded ✅")

# ================================
# 3. PREPARE DATA
# ================================
X = df.select_dtypes(include=['int64','float64']).drop(columns=[
    'y_ponding_hotspot','y_low_lying','y_sparse_drainage','y_extreme_rain_history'
], errors='ignore')

y = df['y_ponding_hotspot']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# 4. TRAIN MODELS
# ================================
lgbm = LGBMClassifier()
cat = CatBoostClassifier(verbose=0)
mlp = MLPClassifier(max_iter=500)
tabnet = TabNetClassifier(verbose=0)

lgbm.fit(X_train, y_train)
cat.fit(X_train, y_train)
mlp.fit(X_train, y_train)

tabnet.fit(
    X_train.values, y_train.values,
    eval_set=[(X_test.values, y_test.values)],
    patience=10,
    max_epochs=100
)

print("Models trained ✅")

# ================================
# 5. GET PROBABILITIES
# ================================
lgbm_pred = lgbm.predict_proba(X_test)[:,1]
cat_pred = cat.predict_proba(X_test)[:,1]
mlp_pred = mlp.predict_proba(X_test)[:,1]
tab_pred = tabnet.predict_proba(X_test.values)[:,1]

# ================================
# 6. DENSITY PLOT (FINAL FIX 🔥)
# ================================
plt.figure(figsize=(10,6), dpi=600)

# Plot each model separately (legend guaranteed)
sns.kdeplot(lgbm_pred, fill=True, label='LightGBM', color='blue', alpha=0.5)
sns.kdeplot(cat_pred, fill=True, label='CatBoost', color='green', alpha=0.5)
sns.kdeplot(mlp_pred, fill=True, label='MLP', color='red', alpha=0.5)
sns.kdeplot(tab_pred, fill=True, label='TabNet', color='orange', alpha=0.5)

plt.xlim(0,1)

plt.title("Density Distribution of Model Predictions", fontsize=14)
plt.xlabel("Predicted Probability of Flood")
plt.ylabel("Density")

# ✅ LEGEND (WORKING 100%)
plt.legend(title="Model", bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()

# SAVE HIGH QUALITY
plt.savefig("density_models_600dpi.png", dpi=600, bbox_inches='tight')
plt.savefig("density_models_600dpi.pdf", bbox_inches='tight')

plt.show()

print("Final Plot Generated ✅ (Legend Fixed + 600 DPI)")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv('flood_model_ready_final.csv')

# Sort by rainfall to simulate event progression
df = df.sort_values(by='rainfall_intensity_mm_hr').reset_index(drop=True)

# Create synthetic time axis
time = np.arange(len(df))

# Rainfall (Hyetograph)
rainfall = df['rainfall_intensity_mm_hr']

# Simulated runoff (Hydrograph)
# You can replace this with real runoff if available
runoff = np.convolve(rainfall, np.ones(10)/10, mode='same')  # smoothing

# ---------------- PLOT ----------------
fig, ax1 = plt.subplots(figsize=(10,6), dpi=600)

# Hyetograph (Rainfall - inverted bars)
ax1.bar(time, rainfall, color='purple', alpha=0.7)
ax1.invert_yaxis()
ax1.set_ylabel("Rainfall Intensity (mm/hr)", color='purple')
ax1.set_xlabel("Time")

# Secondary axis for runoff
ax2 = ax1.twinx()

# Hydrograph (Runoff curve)
ax2.plot(time, runoff, color='red', linewidth=2)
ax2.set_ylabel("Runoff / Flood Response", color='red')

# Mark peak
peak_idx = np.argmax(runoff)
ax2.axvline(peak_idx, linestyle='--', color='black')

# Titles
plt.title("Hyetograph–Hydrograph Plot (Flood Event Simulation)")

plt.tight_layout()
plt.savefig("hyetograph_hydrograph.png", dpi=600)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------------- LOAD DATA ----------------
df = pd.read_csv('flood_model_ready_final.csv')

# ---------------- DATE ----------------
df['event_date'] = pd.to_datetime(df['event_date'])

# ---------------- LABEL COLUMNS ----------------
label_cols = [
    'y_ponding_hotspot',
    'y_low_lying',
    'y_sparse_drainage',
    'y_extreme_rain_history'
]

# ---------------- FLOOD INTENSITY ----------------
df['flood_intensity'] = df[label_cols].sum(axis=1)

# ---------------- AGGREGATION ----------------
data = df.groupby('event_date').agg({
    'rainfall_intensity_mm_hr': 'mean',
    'flood_intensity': 'mean'
}).rename(columns={
    'rainfall_intensity_mm_hr': 'rainfall',
    'flood_intensity': 'flood'
}).sort_index()

# ---------------- SMOOTHING ----------------
data['flood_smooth'] = data['flood'].rolling(window=2, min_periods=1).mean()

# ---------------- PLOT ----------------
fig, ax1 = plt.subplots(figsize=(10,6), dpi=600)

# Rainfall (Hyetograph)
ax1.bar(data.index, data['rainfall'], alpha=0.7)
ax1.invert_yaxis()
ax1.set_ylabel("Rainfall Intensity (mm/hr)")
ax1.set_xlabel("Event Date")

# Flood response (Hydrograph)
ax2 = ax1.twinx()
ax2.plot(data.index, data['flood_smooth'], linewidth=2)
ax2.set_ylabel("Flood Intensity")

# Peak
peak_date = data['flood_smooth'].idxmax()
ax2.axvline(peak_date, linestyle='--')

# Formatting
plt.title("Event-based Hyetograph–Hydrograph ")
plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig("final_hydrograph.png", dpi=600)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------------- LOAD DATA ----------------
df = pd.read_csv('flood_model_ready_final.csv')

# ---------------- DATE ----------------
df['event_date'] = pd.to_datetime(df['event_date'])

# ---------------- LABEL COLUMNS ----------------
label_cols = [
    'y_ponding_hotspot',
    'y_low_lying',
    'y_sparse_drainage',
    'y_extreme_rain_history'
]

# ---------------- FLOOD INTENSITY ----------------
df['flood_intensity'] = df[label_cols].sum(axis=1)

# ---------------- AGGREGATION ----------------
data = df.groupby('event_date').agg({
    'rainfall_intensity_mm_hr': 'mean',
    'flood_intensity': 'mean'
}).rename(columns={
    'rainfall_intensity_mm_hr': 'rainfall',
    'flood_intensity': 'flood'
}).sort_index()

# ---------------- SMOOTHING ----------------
data['flood_smooth'] = data['flood'].rolling(window=2, min_periods=1).mean()

# ---------------- PLOT ----------------
fig, ax1 = plt.subplots(figsize=(10,6), dpi=600)

# 🌧️ Rainfall (Blue)
ax1.bar(data.index, data['rainfall'], color='blue', alpha=0.6, label='Rainfall')
ax1.invert_yaxis()
ax1.set_ylabel("Rainfall Intensity (mm/hr)", color='blue')
ax1.set_xlabel("Event Date")

# 🌊 Flood (Red)
ax2 = ax1.twinx()
ax2.plot(data.index, data['flood_smooth'], color='red', linewidth=2, label='Flood Response')
ax2.set_ylabel("Flood Intensity", color='red')

# Peak line
peak_date = data['flood_smooth'].idxmax()
ax2.axvline(peak_date, linestyle='--', color='black')

# ---------------- LEGEND ----------------
fig.legend(loc="upper right")

# ---------------- TITLE ----------------
plt.title("Event-based Hyetograph–Hydrograph")

plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig("final_hydrograph_colored.png", dpi=600)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------------- LOAD DATA ----------------
df = pd.read_csv('flood_model_ready_final.csv')

# ---------------- DATE ----------------
df['event_date'] = pd.to_datetime(df['event_date'])

# ---------------- LABEL COLUMNS ----------------
label_cols = [
    'y_ponding_hotspot',
    'y_low_lying',
    'y_sparse_drainage',
    'y_extreme_rain_history'
]

# ---------------- FLOOD INTENSITY ----------------
df['flood_intensity'] = df[label_cols].sum(axis=1)

# ---------------- AGGREGATE BY DATE ----------------
data = df.groupby('event_date').agg({
    'rainfall_intensity_mm_hr': 'mean',   # cleaner rainfall
    'flood_intensity': 'mean'
}).rename(columns={
    'rainfall_intensity_mm_hr': 'rainfall',
    'flood_intensity': 'flood'
}).sort_index()

# ---------------- SMOOTH FLOOD ----------------
data['flood_smooth'] = data['flood'].rolling(window=3, min_periods=1).mean()

# ---------------- PLOT ----------------
fig, ax1 = plt.subplots(figsize=(12,6), dpi=600)

# 🌧️ Rainfall (clean bars)
ax1.bar(data.index, data['rainfall'],
        width=5, alpha=0.6)   # wider bars = less clutter
ax1.invert_yaxis()
ax1.set_ylabel("Rainfall Intensity (mm/hr)")

# 🌊 Flood (smooth line)
ax2 = ax1.twinx()
ax2.plot(data.index, data['flood_smooth'], linewidth=2)
ax2.set_ylabel("Flood Intensity")

# Peak
peak_date = data['flood_smooth'].idxmax()
ax2.axvline(peak_date, linestyle='--')

# ---------------- FORMATTING ----------------
plt.title("Cleaned Event-based Hyetograph–Hydrograph")
plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig("clean_hydrograph.png", dpi=600)
plt.show()

import pandas as pd
import folium

df = pd.read_csv("flood_model_ready_final.csv")

# Correct rainfall column
rain_col = 'rainfall_intensity_mm_hr'

# Create map
m = folium.Map(
    location=[df['latitude'].mean(), df['longitude'].mean()],
    zoom_start=5
)

# Add points
for i in range(len(df)):
    folium.CircleMarker(
        location=[df.loc[i, 'latitude'], df.loc[i, 'longitude']],
        radius=5,
        color='blue',
        fill=True,
        fill_opacity=0.6,
        popup=f"{df.loc[i, 'city_name']} | Rainfall: {df.loc[i, rain_col]} mm/hr"
    ).add_to(m)

m.save("rainfall_map.html")

print(df.columns)

top_rainfall = df.sort_values(by=rain_col, ascending=False)

print(top_rainfall[['city_name', rain_col]].head(10))

city_rainfall = df.groupby('city_name')[rain_col].mean().sort_values(ascending=False)

print(city_rainfall.head(10))

# Top 10% threshold
threshold = df[rain_col].quantile(0.90)

m = folium.Map(
    location=[df['latitude'].mean(), df['longitude'].mean()],
    zoom_start=5
)

for i in range(len(df)):

    color = 'red' if df.loc[i, rain_col] >= threshold else 'blue'

    folium.CircleMarker(
        location=[df.loc[i, 'latitude'], df.loc[i, 'longitude']],
        radius=6,
        color=color,
        fill=True,
        fill_opacity=0.7,
        popup=f"{df.loc[i, 'city_name']} | Rainfall: {df.loc[i, rain_col]}"
    ).add_to(m)

m.save("high_rainfall_map.html")

import matplotlib.pyplot as plt
import seaborn as sns

rain_col = 'rainfall_intensity_mm_hr'

plt.figure(figsize=(6,5))

sns.histplot(df[rain_col], kde=True)

plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("Frequency")
plt.title("Distribution of Rainfall Intensity")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("rainfall_distribution.png", dpi=600)

plt.show()

plt.figure(figsize=(6,5))

sns.boxplot(
    x='y_ponding_hotspot',
    y='rainfall_intensity_mm_hr',
    data=df,
    palette=['blue','red']
)

plt.xlabel("Flood (0 = No, 1 = Yes)")
plt.ylabel("Rainfall Intensity (mm/hr)")
plt.title("Rainfall vs Flood Occurrence")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("rainfall_vs_flood.png", dpi=600)

plt.show()

# Get top 10 cities by avg rainfall
top_cities = (
    df.groupby('city_name')['rainfall_intensity_mm_hr']
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(7,5))

sns.barplot(
    x=top_cities.values,
    y=top_cities.index,
    palette='viridis'
)

plt.xlabel("Avg Rainfall Intensity (mm/hr)")
plt.ylabel("City")
plt.title("Top 10 Cities by Rainfall Intensity")

plt.tight_layout()
plt.savefig("top_rainfall_cities.png", dpi=600)

plt.show()

plt.figure(figsize=(7,6))

scatter = plt.scatter(
    df['longitude'],
    df['latitude'],
    c=df['rainfall_intensity_mm_hr'],
    cmap='coolwarm',
    s=20
)

plt.colorbar(scatter, label="Rainfall Intensity (mm/hr)")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Spatial Distribution of Rainfall Intensity")

plt.tight_layout()
plt.savefig("rainfall_map_static.png", dpi=600)

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

rain_col = 'rainfall_intensity_mm_hr'

# Top 10 cities
top_df = (
    df.groupby('city_name')[rain_col]
    .mean()
    .sort_values(ascending=False)
    .head(50)
    .reset_index()
)

# Create categories
def categorize(val):
    if val < 20:
        return 'Low'
    elif val < 50:
        return 'Medium'
    else:
        return 'High'

top_df['Rainfall Level'] = top_df[rain_col].apply(categorize)

# Plot
plt.figure(figsize=(10,10))

sns.barplot(
    data=top_df,
    x=rain_col,
    y='city_name',
    hue='Rainfall Level',
    palette={'Low':'blue', 'Medium':'orange', 'High':'red'}
)

plt.xlabel("Avg Rainfall Intensity (mm/hr)")
plt.ylabel("City")
plt.title("Top 10 Cities by Rainfall Intensity")

plt.legend(title="Rainfall Level")

plt.tight_layout()
plt.savefig("top_rainfall_cities_with_legend.png", dpi=600)

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Target column
target_col = 'y_ponding_hotspot'

# Count values
counts = df[target_col].value_counts().sort_index()

# Plot
plt.figure(figsize=(6,5))

sns.barplot(
    x=counts.index,
    y=counts.values,
    palette=['#4C72B0', '#DD8452']  # Blue = Non-Flood, Orange = Flood
)

# Labels
plt.xlabel("Class", fontsize=12)
plt.ylabel("Count", fontsize=12)
plt.title("Class Distribution of Flood Occurrence", fontsize=14)

# Custom tick labels
plt.xticks([0,1], ['Non-Flood (0)', 'Flood (1)'])

# Add values on top
for i, v in enumerate(counts.values):
    plt.text(i, v + max(counts.values)*0.01, str(v), ha='center', fontsize=11)

# Grid
plt.grid(axis='y', linestyle='--', alpha=0.4)

# Save (poster quality)
plt.tight_layout()
plt.savefig("class_distribution.png", dpi=600)

plt.show()